apiVersion: v1
kind: Service
metadata:
  name: netbird-dns-udp
  namespace: netbird-dns
spec:
  selector:
    app: netbird-dns
  ports:
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-dns-tcp
  namespace: netbird-dns
spec:
  selector:
    app: netbird-dns
  ports:
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
  type: LoadBalancer
